spring:
  application:
    name: context-practice
  profiles:
    active: dev

server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
